command_timeout = 2500

[aws]
symbol = "  "

[buf]
symbol = " "
format = '(with [$symbol($version )]($style))'

[c]
symbol = " "
format = '(via [$symbol($version(-$name) )]($style))'

[conda]
symbol = " "

[crystal]
symbol = " "
format = '(via [$symbol($version )]($style))'

[dart]
symbol = " "
format = '(via [$symbol($version )]($style))'

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "
format = '(via [$symbol($version \(OTP $otp_version\) )]($style))'

[elm]
symbol = " "
format = '(via [$symbol($version )]($style))'

[fennel]
symbol = " "
format = '(via [$symbol($version )]($style))'

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "
format = '(via [$symbol($version )]($style))'

[guix_shell]
symbol = " "

[haskell]
symbol = " "
format = '(via [$symbol($version )]($style))'

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = '(via [$symbol($version )]($style))'

[julia]
symbol = " "
format = '(via [$symbol($version )]($style))'

[kotlin]
symbol = " "
format = '(via [$symbol($version )]($style))'

[lua]
symbol = " "
format = '(via [$symbol($version )]($style))'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "
format = '(via [$symbol($version )]($style))'

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = '(via [$symbol($version )]($style))'

[ocaml]
symbol = " "
format = '(via [$symbol($version )(\($switch_indicator$switch_name\) )]($style))'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
format = '(is [$symbol$version]($style) )'

[perl]
symbol = " "
format = '(via [$symbol($version )]($style))'

[php]
symbol = " "
format = '(via [$symbol($version )]($style))'

[pijul_channel]
symbol = " "

[python]
symbol = " "
format = '(via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style))'

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "
format = '(via [$symbol($version )]($style))'

[rust]
symbol = "󱘗 "
format = '(via [$symbol($version )]($style))'

[scala]
symbol = " "
format = '(via [$symbol($version )]($style))'

[swift]
symbol = " "
format = '(via [$symbol($version )]($style))'

[zig]
symbol = " "
format = '(via [$symbol($version )]($style))'

[gradle]
symbol = " "

[spack]
symbol = "🅢 "

[bun]
format = '(via [$symbol($version )]($style))'

[cmake]
format = '(via [$symbol($version )]($style))'

[cobol]
format = '(via [$symbol($version )]($style))'

[daml]
format = '(via [$symbol($version )]($style))'

[deno]
format = '(via [$symbol($version )]($style))'

[dotnet]
format = '(via [$symbol($version )(🎯 $tfm )]($style))'

[erlang]
format = '(via [$symbol($version )]($style))'

[helm]
format = '(via [$symbol($version )]($style))'

[opa]
format = '(via [$symbo($version ]($style))"'

[purescript]
format = '(via [$symbol($version )]($style))'

[raku]
format = '(via [$symbol($version-$vm_version )]($style))'

[red]
format = '(via [$symbol($version )]($style))'

[vagrant]
format = '(via [$symbol($version )]($style))'

[vlang]
format = '(via [$symbol($version )]($style))'
